export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE";


export const GET_SINGLE_PERSON_REQUEST="GET_SINGLE_PERSON_REQUEST";
export const GET_SINGLE_PERSON_SUCCESS="GET_SINGLE_PERSON_SUCCESS";
export const GET_SINGLE_PERSON_FAILURE="GET_SINGLE_PERSON_FAILURE";


export const FETCH_SERVERRATES_REQUEST="FETCH_SERVERRATES_REQUEST";
export const FETCH_SERVERRATES_SUCCESS="FETCH_SERVERRATES_SUCCESS";
export const FETCH_SERVERRATES_FAILURE="FETCH_SERVERRATES_FAILURE";
